name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15, windows-2019]

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies (Linux)
      run: |
        sudo apt install libboost-system-dev
        git clone https://github.com/fmtlib/fmt.git
        cd fmt
        git checkout 6.2.1
        mkdir build
        cd build
        cmake .. -DFMT_TEST=OFF
        make -j2
        sudo make install
        cd ../..
        git clone https://github.com/CLIUtils/CLI11.git
        cd CLI11
        git checkout v1.9.0
        mkdir build
        cd build
        cmake .. -DCLI11_BUILD_TESTS=OFF
        make -j2
        sudo make install
        cd ../..
      if: matrix.os == 'ubuntu-18.04'

    - name: Install dependencies (MacOs)
      run: |
        brew update
        brew install boost
        git clone https://github.com/fmtlib/fmt.git
        cd fmt
        git checkout 6.2.1
        mkdir build
        cd build
        cmake .. -DFMT_TEST=OFF
        make -j2
        sudo make install
        cd ../..
        git clone https://github.com/CLIUtils/CLI11.git
        cd CLI11
        git checkout v1.9.0
        mkdir build
        cd build
        cmake .. -DCLI11_BUILD_TESTS=OFF
        make -j2
        sudo make install
        cd ../..
      if: matrix.os == 'macos-10.15'

    - name: Install dependencies (Windows)
      run: |
        choco install boost-msvc-14.1
        git clone https://github.com/fmtlib/fmt.git
        cd fmt
        git checkout 6.2.1
        mkdir build
        cd build
        cmake .. -DFMT_TEST=OFF
        cmake --build . --target install
        cd ../..
        git clone https://github.com/CLIUtils/CLI11.git
        cd CLI11
        git checkout v1.9.0
        mkdir build
        cd build
        cmake .. -DCLI11_BUILD_TESTS=OFF
        cmake --build . --target install
        cd ../..
      if: matrix.os == 'windows-2019'

    - name: Configure
      run: |
        cd $GITHUB_WORKSPACE
        ls
        mkdir build
        ls
        cd build
        ls
        cmake ..

    - name: Build
      run: |
        cd $GITHUB_WORKSPACE/build
        cmake --build .

    - name: Test
      run: |
        cd $GITHUB_WORKSPACE/build
        cmake --test .
